In [2]:
import numpy as np

<font color = 'yellow'> NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.</font>

<font color = 'green'> Numpy arrays take in __sequence__ ds such as __strings__, __lists__ and __tuples__ as argument to cast them into np arrays.</font>

In [46]:
# creating an array
a = np.array([1,2,3,4,5])
print(a)
print(type(a))
print(a.shape) # It is not a method but an attribute which tells about the dimensions of the array

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [47]:
b = np.array([[1],[2],[3],[4]])
print(b)
print(type(b))
print(b.shape) # 4x1 : 4 rows 1 column

[[1]
 [2]
 [3]
 [4]]
<class 'numpy.ndarray'>
(4, 1)


In [48]:
c = np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)
print(c[1][1])

[[1 2 3]
 [4 5 6]]
(2, 3)
5


<font color = 'red'> custom arrays</font>

In [51]:
# create Zeros, Ones, Cutom arrays, Identity matrix, Random matrix
a = np.zeros((3,3)) # dimension packed in a tuple 
print(a)

b = np.ones((2,3)) 
print(b)

c = np.full((3,2),5) # first dimension then value
print(c)

d = np.eye(4) # identitiy matrix
print(d)

e = np.random.random((2,3)) # random.randint(i,size=(x,y)) : numbers bw 1 to i, of size x by y 
print(e)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.85650739 0.46209821 0.81712818]
 [0.96597998 0.28077519 0.62190258]]


We can read and update the values of these arrays.

<font color = 'yellow'> For matrix e, [ , ] which holds 2 values [rows, columns]
<br> We can do slicing for these as well

In [65]:
# Ways to read using slicing 

# To read column-2 of e matrix
print(e[:,2]) # We need all rows so '[:,' and 2nd column so '2]'
 
# To read last 2 values of last row in e matrix
print(e[1 ,1:]) # In row 1 we need all elements from 1

[0.81712818 0.62190258]
[0.28077519 0.62190258]


<font color = 'red'> The datatype can also be mentioned at the time of declaration <font>

In [69]:
a = np.zeros((3,2),dtype = np.int64)
print(a)
print(a.dtype) 
# By default it is float 

[[0 0]
 [0 0]
 [0 0]]
int64


<font color = 'yellow'> Other mathamatical operations such as <font color = 'red'> __addition of arrays, subtraction, multiplication, dot product, division, square root, sum__</font>.. are inbuilt </font>
<br>
<font color = 'darkgreen'> axis can also be mentioned (optional) which performs the operation based on the value defined i.e <font color = 'grey'> __axis = 0__ would mean, carry out operation for __column__ and __axis = 1__ would mean carry out operation for __row__ <font>

 <font color = 'yellow'> Multiplication does an element wise multiplication of two matrices, while a dot is the dot product of two matrices </font>

In [10]:
# Some examples:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.array([[10,20,30],[40,50,60],[70,80,90]])

print(np.multiply(x,y))
print(np.divide(x,y)) # or print(x/y) also works
print(np.sqrt(x))

[[ 10  40  90]
 [160 250 360]
 [490 640 810]]
[[0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [11]:
# Matrix multiplication/ dot products
print(x.dot(y))
print(np.dot(x,y))

[[ 300  360  420]
 [ 660  810  960]
 [1020 1260 1500]]
[[ 300  360  420]
 [ 660  810  960]
 [1020 1260 1500]]


In [12]:
print(np.sum(x))

45


In [15]:
print(np.sum(x,axis=0)) # Along colum
print(np.sum(x,axis=1)) # Along row

[12 15 18]
[ 6 15 24]


In [16]:
# Stacking of arrays
np.stack((x,y),axis = 1) # merging arrays

array([[[ 1,  2,  3],
        [10, 20, 30]],

       [[ 4,  5,  6],
        [40, 50, 60]],

       [[ 7,  8,  9],
        [70, 80, 90]]])

In [31]:
# Reshaping a numpy array
a = np.array([[1,2,3],[4,5,6]])
print(a)
a = a.reshape(3,2)
print(a)
a = a.reshape(3,-1) # if a dimension is not known then put -1 in place of it   
print(a)
a = a.reshape(-1,2)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [5]:
matrix = np.array([[10,24,4,17],[21,17,12,2],[41,16,7,3]])

# Max element in a matrix
print(np.max(matrix))

# Min element in a matrix
print(np.min(matrix))

41
2


<font color ='yellow'> To find out the index of min/max element is the matrix/array </font>

In [26]:
vector = np.array([14,7,5,15,16,2,18])

print(np.argmin(vector))
print(np.argmax(vector))

# To get an array of unique elements out of the original array 

dup_ar = np.array([2,16,4,1,1,4,2,2,2,16,18,17,13,-1,-5,-1])

unique1 = np.unique(dup_ar) # Returns in a sorted order
print(unique1)

unique2 = np.unique(dup_ar,return_counts = True) # a tuple of array and frequency of elements in that array
print(unique2) 

5
6
[-5 -1  1  2  4 13 16 17 18]
(array([-5, -1,  1,  2,  4, 13, 16, 17, 18]), array([1, 2, 2, 4, 2, 1, 2, 1, 1], dtype=int64))


In [28]:
# To find out the element with the highest frequency 
index_of_max = np.argmax(unique2[1])
print(unique2[0][index_of_max])

2
