## Numpy Random Module

- rand : Random values in a given shape.
- randn : Returns a sample(or samples) from the 'standard normal' distribution.
- randInt : Returns random integers from low(inclusive) to high(exclusive).
- random : Returns random floats in the half-open interval [0.0,1.0]
- choice : Generates a random sample from a given 1-D array 
- shuffle : Shuffles the contents of a sequence

In [1]:
import numpy as np

In [3]:
# Arange (not a part of random module) but gives out an array filled with elements from 0 to n-1
a = np.arange(10) 
print(a)

b = np.arange(10) + 5 # can give out the starting value
print(b)

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]


In [98]:
np.random.shuffle(a)
print(a)

# Generating a array of randoms

c = np.random.randint(10,20,5) # 5 randoms bw [10,20)
print(c)

# Randomly pick an element from an array
element = np.random.choice([1,17,11,13,7,14,-21])
print(element)

[8 3 2 1 9 4 5 6 7 0]
[15 13 18 18 10]
-21


#### For random number generators to generate numbers in the same order we've to set seed as 1 in the begining.
<br> <font color = 'skyblue'>These rand.. are pseudo random i.e: 
<br>-  When a random number is generated, a series of random numbers is generated following it
<br>and the next time we run the notebook, a different series might get generated starting from a different random number.
<br>- seed(1) will store the state of the random numbers so that next time we run the notebook, the generator generates the same set of random numbers as it generated earlier (we can replicate our results).</font>

In [2]:
np.random.seed(1)

In [4]:
aux = np.random.randint(5,20,10) 
print(aux)
# same series will get generated everytime we run this notebook after executing cekk with seed(1)

[17 12 18 17 11 14  7  9 19 10]
