## stats
- min,max
- mean
- median
- average
- variance
- standard deviation

In [2]:
import numpy as np

In [3]:
# min/ max
matrix = np.array([[1,2,3,4],[4,3,2,1]])

print(np.min(matrix))

print(np.min(matrix,axis = 0))
print(np.min(matrix,axis = 1))

1
[1 2 2 1]
[1 1]


In [14]:
# mean 
vector = np.array([1,2,3,4,5,6])
print(np.mean(vector))

# median 
print(np.median(vector))

matrix =  np.array([[1,12,13,43],[4,73,21,17]])
print(np.mean(matrix))
print(np.mean(matrix, axis = 0))
print(np.mean(matrix, axis = 1))

3.5
3.5
23.0
[ 2.5 42.5 17.  30. ]
[17.25 28.75]


In [17]:
# Average
print(np.average(vector))

# But we can even pass weights of each elements to average function 

wts = np.array([10,20,30,40,50,60])
print(np.average(vector,weights = wts))

3.5
4.333333333333333


In [22]:
# variance and standard deviation 
print(np.std(vector)) 
print(np.var(vector)) 

1.707825127659933
2.9166666666666665


In [41]:
aux = np.array([10,10,10,10,10,10])
x = 7
print(sum(aux-x)) # reducing 7 from every element while obtaining sum 

18


In [63]:
a = np.random.randint(0,15, size=(4,4))
print(a[np.any((a >= 5) & (a <= 10))])

[[[ 7 13  1  6]
  [ 0  3 14 11]
  [ 4  5  2 11]
  [ 2  1  2  2]]]


In [66]:
print(a[np.where((a >= 5) & (a <= 10))])

[7 6 5]
